FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./turbo.json ./turbo.json

COPY ./package.json ./package.json

COPY ./package-lock.json ./package-lock.json

COPY ./apps/http-backend ./apps/http-backend

RUN npm install
RUN npm run db:generate
RUN npm run build

EXPOSE 8081

CMD [ "npm", "run", "start:backend" ]