FROM node:20-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages

COPY ./turbo.json ./turbo.json

COPY ./package.json ./package.json

COPY ./package-lock.json ./package-lock.json

COPY ./apps/ws-backend ./apps/ws-backend

RUN npm install
RUN npm run db:generate
RUN DATABASE_URL=${DATABASE_URL} npm run build

EXPOSE 8080

CMD [ "npm", "run", "start:websocket" ]